export const LUCIDE_ICONS = [
  'Banknote', 'Briefcase', 'Car', 'Coffee', 'CreditCard', 'Gamepad2',
  'GraduationCap', 'HeartPulse', 'Home', 'Lightbulb', 'ShoppingBag',
  'Utensils', 'Tag', 'Plane', 'Bus', 'Train', 'Fuel', 'Shirt', 'Gift',
  'Music', 'Film', 'Tv', 'Phone', 'Wifi', 'Zap', 'Droplet', 'Flame',
  'Snowflake', 'Sun', 'Moon', 'Baby', 'Dog', 'Cat', 'Trees', 'Flower2',
  'Apple', 'Pizza', 'Wine', 'Beer', 'Cigarette', 'Pill', 'Stethoscope',
  'Dumbbell', 'Bike', 'Footprints', 'Scissors', 'Paintbrush', 'Wrench',
  'Hammer', 'Key', 'Lock', 'Shield', 'BookOpen', 'Newspaper', 'Mail',
  'MessageSquare', 'Camera', 'Image', 'MapPin', 'Navigation', 'Globe',
  'Building', 'Building2', 'Store', 'Warehouse', 'Church', 'Landmark',
  'PiggyBank', 'Wallet', 'Receipt', 'BadgeDollarSign', 'TrendingUp',
  'TrendingDown', 'BarChart', 'PieChart', 'Calculator', 'Percent',
  'HandCoins', 'CircleDollarSign', 'Coins', 'DollarSign', 'IndianRupee',
  'Sparkles', 'Heart', 'Star', 'Trophy', 'Award', 'Crown', 'Gem', 'Rocket',
  'Laptop', 'Monitor', 'Smartphone', 'Tablet', 'Watch', 'Headphones',
  'Speaker', 'Printer', 'HardDrive', 'Cpu', 'MemoryStick',
  'UtensilsCrossed', 'ChefHat', 'Salad', 'Soup', 'IceCream', 'Cake',
  'Cookie', 'Popcorn', 'Sandwich', 'Egg', 'Fish', 'Beef', 'ShoppingCart',
  'Package', 'Truck', 'Ship', 'Ambulance', 'Siren', 'Bed', 'Bath', 'Sofa',
  'Lamp', 'Fan', 'AirVent', 'Refrigerator', 'WashingMachine', 'Microwave',
  'Tv2',
] as const;
